### ISSUE TITLE
missing (apache) license file 

### ISSUE THREAD

**Issue by ghost** [basho/rt#1]
Hey Goncalo - would you mind adding a license file to this project - typically everything Basho comes with an Apache 2 license.

**Comment by goncalotomas** [comment]
@bryanhuntesl I guess this slipped my mind. Sorry!
I've copied over an Apache 2 license file from another project, so let me know if I need to add the license header into the source files.

**Comment by ghost** [comment]
Nah - just having the LICENSE file is good - no need to pollute every file. Thanks man.
